// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrWAaD9Xrm4AEgk7BSBMxwtUo-ERV58Og',
    appId: '1:874807678932:web:967692c09088efbc586841',
    messagingSenderId: '874807678932',
    projectId: 'money-manger-61f3c',
    authDomain: 'money-manger-61f3c.firebaseapp.com',
    storageBucket: 'money-manger-61f3c.appspot.com',
    measurementId: 'G-4ZLJ06HR5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtXc_QXuXY3f95jxtXsDT642QCxHoqAqw',
    appId: '1:874807678932:android:b4b00e6c326aaec7586841',
    messagingSenderId: '874807678932',
    projectId: 'money-manger-61f3c',
    storageBucket: 'money-manger-61f3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnfWitZm-nRE140Hdggx9FIX5mLpJYH2Y',
    appId: '1:874807678932:ios:9dd7a7af43c6767b586841',
    messagingSenderId: '874807678932',
    projectId: 'money-manger-61f3c',
    storageBucket: 'money-manger-61f3c.appspot.com',
    iosClientId: '874807678932-fstqhpcstvu3v3l24o164gap0uilid9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentCourse',
  );
}
